import { S } from './types';
export declare const errBasic: (msg?: S) => Error;
export declare const errType: (msg?: S) => TypeError;
export declare const errEval: (msg?: S) => EvalError;
export declare const errRange: (msg?: S) => RangeError;
export declare const errSyntax: (msg?: S) => SyntaxError;
export declare const errReference: (msg?: S) => ReferenceError;
export declare const ERROR_BASIC: Error;
export declare const ERROR_TYPE: TypeError;
export declare const ERROR_EVAL: EvalError;
export declare const ERROR_RANGE: RangeError;
export declare const ERROR_SYNTAX: SyntaxError;
export declare const ERROR_REFERENCE: ReferenceError;
export declare const ERROR_TYPE_NOT_STRING: TypeError;
export declare const ERROR_TYPE_NOT_ARRAY: TypeError;
export declare const ERROR_VALUE: TypeError;
export declare const ERROR_VALUE_NOT_DEFINED: TypeError;
export declare const ERROR_VALUE_NOT_TRUTHY: TypeError;
export declare const ERROR_LENGTH: TypeError;
export declare const ERROR_LENGTH_SHORT: TypeError;
export declare const ERROR_LENGTH_LARGE: TypeError;
