import { A, S } from './types';
export declare const NOTES: A<S>;
export declare const NOTES_ALTERNATE: A<S>;
export declare const SCALES: A<S>;
export declare const COLOR_CLASSNAMES: A<S>;
export declare const COLOR_NAMES: A<S>;
export declare const COLOR_CODES: A<S>;
export declare const DURATION_CHARS: A<S>;
export declare const INTERVAL_CHARS: A<S>;
export declare const Constants: {
    NOTES: A<string>;
    NOTES_ALTERNATE: A<string>;
    SCALES: A<string>;
    COLOR_CLASSNAMES: A<string>;
    COLOR_NAMES: A<string>;
    COLOR_CODES: A<string>;
    DURATION_CHARS: A<string>;
    INTERVAL_CHARS: A<string>;
};
export declare const ConstantValues: {
    Notes: A<string>;
    NotesAlternate: A<string>;
    Scales: A<string>;
    ColorClassnames: A<string>;
    ColorNames: A<string>;
    ColorCodes: A<string>;
    DurationChars: A<string>;
    IntervalChars: A<string>;
    NOTES: A<string>;
    NOTES_ALTERNATE: A<string>;
    SCALES: A<string>;
    COLOR_CLASSNAMES: A<string>;
    COLOR_NAMES: A<string>;
    COLOR_CODES: A<string>;
    DURATION_CHARS: A<string>;
    INTERVAL_CHARS: A<string>;
};
export default ConstantValues;
